#- name: EF_GPIO8
#  repo: efabless/EF_GPIO8.git
#  fw: false
#  docs: false
#  bus_wrapper: false
#- name: EF_UART
#  repo: efabless/EF_UART.git
#- name: EF_TMR32
#  repo: efabless/EF_TMR32.git
- name: EF_QSPI_XIP_CTRL
  fw: false
  wrapper: false
  repo: efabless/EF_QSPI_XIP_CTRL.git
#- name: OL-DFFRAM
#  repo: efabless/OL-DFFRAM.git
- name: EF_SPI
  repo: efabless/EF_SPI.git
#- name: EF_I2C
#  repo: efabless/EF_I2C.git
#- name: EF_I2S
#  repo: efabless/EF_I2S.git
#- name: EF_PSRAM_CTRL_V2
#  repo: efabless/EF_PSRAM_CTRL_V2.git
